version: '3.1'

services:

  mongo:
    image: mongo:5.0
    hostname: bibi
    container_name: bibi-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    ports:
      - 27017:27017

  my-workout-api:
    image: mariospapaz/my-workout:1.0
    hostname: api 
    container_name: my-workout-api
    restart: on-failure

    ports:
      - 25585:25585