name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main] 

jobs:
  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grabing repository
        run: |
          echo "Pong!"
   
      - name: Bot
        uses: peter-evans/commit-comment@v1
        with:
          body: |
              Your application is released to the cloud! ☁️

  on-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Bot
        uses: peter-evans/commit-comment@v1
        with:
          body: |
              CI broke >:(
              
