name: CD

on:
  workflow_run:
    workflows: 
      - "CI"
    types: 
      - completed

jobs:
  on-success:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Grabing repository
        run: |
          echo "Pong!"
   
      - name: Bot
        uses: peter-evans/commit-comment@v1
        with:
          body: |
              Your application is released to the cloud! ☁️

  on-failure:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Bot
        uses: peter-evans/commit-comment@v1
        with:
          body: |
              CI broke >:(
              
